// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT_-W_tB6LXhrlUcDOIrlGZVunnqVpjsM',
    appId: '1:1031831564833:web:234774217ef30dc8742960',
    messagingSenderId: '1031831564833',
    projectId: 'fir-mastering-2df8f',
    authDomain: 'fir-mastering-2df8f.firebaseapp.com',
    storageBucket: 'fir-mastering-2df8f.appspot.com',
    measurementId: 'G-VZFTXYXK0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEr3aISE9U5cYkKDv25wf1L-HOmVZBbYA',
    appId: '1:1031831564833:android:8329b96c1aeb0b82742960',
    messagingSenderId: '1031831564833',
    projectId: 'fir-mastering-2df8f',
    storageBucket: 'fir-mastering-2df8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB369Hw8VD0AEIK4giW9DtB3mZRMdEfYGg',
    appId: '1:1031831564833:ios:8cdaca4f39dcbb12742960',
    messagingSenderId: '1031831564833',
    projectId: 'fir-mastering-2df8f',
    storageBucket: 'fir-mastering-2df8f.appspot.com',
    iosBundleId: 'com.example.masteringFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB369Hw8VD0AEIK4giW9DtB3mZRMdEfYGg',
    appId: '1:1031831564833:ios:bf3858902040beca742960',
    messagingSenderId: '1031831564833',
    projectId: 'fir-mastering-2df8f',
    storageBucket: 'fir-mastering-2df8f.appspot.com',
    iosBundleId: 'com.example.masteringFirebase.RunnerTests',
  );
}
